### PR TITLE
Adds Babel to transpile object rest/spread operator.

### PR DESCRIPTION
**Pull request by DevanB**
Also removes stray commas causing errors.

### CODE REVIEW

**Comment by schickling** [comment]
Thanks for the PR @DevanB but this is not needed and should work out of the box with TypeScript :)

**Comment by DevanB** [comment]
I'm on Node `v8.1.4` and npm `v5.0.3` and I still get that `...` is an unexpected token even with your latest update to add the Node engine to `package.json`

tsconfig.json isn't building the `example` folder, and [object rest/spread hasn't moved to stage 4](https://github.com/tc39/proposal-object-rest-spread) so I believe you still need a transpiling step to convert it? I think Node added it in v8, but it is behind the harmony flag, still. 

Are you able to successfully run the example, @schickling?

**Comment by schickling** [comment]
Yes I am @DevanB. I'm running the following version:

image

**Comment by DevanB** [comment]
Hmm, weird. I'm missing something then. I'll keep investigating.

**Comment by DevanB** [comment]
Weird updating from `v8.1.4` -> `v8.9.3` fixed it.

Thanks for the information @schickling! 🥇

**Pull request closed without merging**
